### ISSUE TITLE
Feature request: Ability to GET params, too.

### ISSUE THREAD

**Issue by amaisano** [rpetti/vmcli#1]
GetParameterFloat and GetParameterString maybe? All we can do with this is set items (which is great).

**Comment by rpetti** [comment]
I've got a basic implementation of this I want to run by you.

The command line options are the same as before, except when you exclude `!` or `=` from the parameter it will print the current value of the parameter instead of setting them:

```
> .\vmcli.exe Strip[0].Gain
Strip[0].Gain=2.000
```

It can also get multiple parameters at once:

```
> .\vmcli.exe Strip[0].Gain Strip[0].B1.Mute Strip[1].Gain
Strip[0].Gain=2.000
Strip[0].B1.Mute=0.000
Strip[1].Gain=0.000
```

The only limitation seems to be that the API doesn't support getting Bus device names... Haven't found a work-around for that unfortunately.

Let me know what you think!

**Comment by amaisano** [comment]
Yeah this is amazing! I originally tried `?Strip[0].Gain` naiively thinking it would ask for the current gain, as a syntax guess, but now I realize it wasn't there to begin with.

Excluding the ! is good too. Thanks!

**Comment by rpetti** [comment]
And it's out in v1.3!

Thanks for the suggestion!

**Comment by amaisano** [comment]
Ah, just noticed your readme may need updating. Some examples are missing the now-important `!` for Set like this one https://twitter.com/tomwarren/status/1564560637409329152?s=20&t=PgestE0MRC6HIb5UONtfWA

**Comment by rpetti** [comment]
Not sure what you mean? The examples are all valid and should cover all use-cases, and the example you've provided is a link to an unrelated twitter post.

**Comment by amaisano** [comment]
Sorry, bad copy pasta.

![image](https://user-images.githubusercontent.com/688435/187494985-ce303973-7c11-4996-bc8d-d915766bc797.png)

I was under the impression that starting now, if you exclude the `!`, you will be performing a get rather than set. Your examples show some SET commands without the `!`. 

I see now (read too fast) that it also still uses SET if you include an equals sign, didn't catch that before.

**Comment by rpetti** [comment]
Yeah, sorry, bad wording on my part. It'll do a get if you don't to a set `=` or a toggle `!` operation.
