### ISSUE TITLE
Error Logging Into Voicemeeter

### ISSUE THREAD

**Issue by royaltongue** [rpetti/vmcli#2]
Not sure if this is still maintained, but I am trying to run `vmcli Strip[o].B3=0` from an `sshexec` node in Node Red. When trying, it returns this error with code `4294967295`.

Here's a picture of the  debug output from Node Red:
![image](https://github.com/rpetti/vmcli/assets/61848270/dc1690ea-8bf3-43f3-a042-01d1962ab823)

Running the same command from a local Powershell session works fine, using the same user as I am to run the command over SSH

**Comment by rpetti** [comment]
Strip index should be an integer, not 'o', but I assume that's just a typo on the issue.

I'm not familiar with Node-RED or its sshexec tasks... But I assume that whatever mechanism the voicemeeter SDK uses to communicate with voicemeeter needs to be done from the same desktop session. If you are somehow executing the command over SSH (I didn't think Windows had a supported SSH server) I doubt that would work.

So if this is for controlling a windows-based audio system remotely, you'd probably need to have it auto-login to the desktop, and have Startup script or scheduled tasks that start voicemeeter and some sort of agent that can call vmcli when asked to. Does Node-RED have a concept of an agent that can be run in the foreground that can be used instead of trying to remote execute it over SSH?

**Comment by royaltongue** [comment]
Just in case it matters, the command works both as `vmcli Strip[0].B3=0` and `vmcli Strip[o].B3=0` when running from my local machine.

Using another physical machine to SSH in and run the command, I get the same error.

It's there a way I can specify the path to the Voicemeeter DLL or whatever this connects to? I'm thinking maybe it just can't locate it over the SSH session.

For what it's worth, Windows 10/11 can run OpenSSH once it's enabled (built in but disabled by default). Node Red unfortunately doesn't have any integration for Voicemeeter.

**Comment by rpetti** [comment]
Sorry, but I genuinely do not know what mechanism the Voicemeeter SDK uses to connect to Voicemeeter. The CLI is just a very simple wrapper around it. If it's not working from the context of the SSH daemon, then my guess is that it needs to be executed from the same desktop session that Voicemeeter is running in.

If Node-RED has an agent for executing arbitrary commands locally on the system it's running on, then starting it in the foreground along with Voicemeeter should do the trick.

Alternatively, you may need to write something that you can run in the foreground that waits for a signal of some kind from Node-RED and then runs the CLI. It may be worth looking into doing that using one of the already existing Voicemeeter remote APIs, such as the one for Python.

**Comment by RagnarJensen** [comment]
I can confirm the "Error logging in to Voicemeeter" when running over a SSH session.
It doesn't affect me, I dont remote in to Voicemeeter that way, I just got curious and tried it out.

@royaltongue Have you considered using VBAN text messages? I don't now the first thing about Node Red, but there seems to exist something.
https://flows.nodered.org/node/node-red-contrib-vban

Edit: It does work if I use my MobaXterm SSH server.

**Comment by royaltongue** [comment]
@RagnarJensen VBAN text is actually I just noticed earlier while looking through the Voicemeeters docs, so I'll definitely have to look more into it. If I can send this mute command over VBAN text, I don't see why it wouldn't work.

Interesting about MobaXterm. I tried from Powershell within Windows Terminal, as well as a bash session from an Ubuntu terminal session

EDIT: Yeah, VBAN send text does literally the same thing, so that contrib **should** work perfectly. I'll post back once I've gotten time to test it

**Comment by royaltongue** [comment]
And now that I try, I remember why I couldn't go down this path. I have Node Red running in a docker container, and it can't reach the computer that's running VBAN without the help of Tailscale. Unfortunately, VBAN absolutely refuses to start accepting connections on my Tailscale interface. As far as I can tell, there's no way to manually bind it, and trying to rename my interfaces to get VBAN to pick it up didn't work -.-

@RagnarJensen Can you tell me what settings you used for your MobaXTerm SSH session? I just tried and am still getting this error

EDIT: Sorry, I misunderstood what you said. Running a the MobaXTerm SSH server on port 23 and connecting through that does allow me to run vmcli commands. I guess OpenSSH handles something differently in this regard

**Comment by royaltongue** [comment]
Even more interestingly, actually installing the full MobaSSH server falls back to the same behavior as OpenSSH. I can literally have one session open from MobaSSH on port 22, and another using the portable SSH server inside MobaXTerm on port 23, and it works on 23 and not 22.

Something to do with the paths set in SSH session, but I cannot figure it out. This has nothing to do with vmcli anymore, so feel free to close this if you think it's too off-topic

**Comment by rpetti** [comment]
Yeah, you're definitely hitting a limitation in the SDK, in particular how it can't seem to communicate between windows sessions. It's not something that can be fixed in vmcli.

I'm assuming you are starting MobaXTerm's portable SSH interactively from the same login session as Voicemeeter, so that's why it's working in that case. Once you install it as a service, it ends up in a different login session entirely and ceases to work.

You'll very likely need to run vmcli in the same session that's running Voicemeeter in order for it to work. That means setting up some other process to run in that session to execute it when you need it to.

This could be as simple as a powershell script that watches a file or directory for instructions to execute using vmcli, then you can use a command over SSH to drop stuff into it. You could also use something like EventGhost running in that desktop session, which has plugins for taking all sorts of actions based off all sorts of events, including webhooks. This is what I've used in the past for automating Voicemeeter when I still used Windows, switching settings around when I started up VR as an example.

Good luck in any case!
